# Generated by Django 2.1.7 on 2019-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(default=False, upload_to='akbar'),
        ),
    ]
